// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"restaurant_project/internal/di/providers"
	"restaurant_project/internal/infrastructure/config"
	"restaurant_project/internal/infrastructure/database"
	"restaurant_project/internal/infrastructure/migration"
	"restaurant_project/internal/presentation/http/handler"
)

// Injectors from wire.go:

// InitializeApp là injector function - Wire sẽ tự động generate code
// để tạo App với tất cả dependencies
func InitializeApp() (*App, error) {
	config := providers.ProvideConfig()
	mongoDBConfig := providers.ProvideMongoDBConfig(config)
	mongoDBConnection := providers.ProvideMongoDBConnection(mongoDBConfig)
	redisConfig := providers.ProvideRedisConfig(config)
	redisConnection := providers.ProvideRedisConnection(redisConfig)
	mySQLConfig := providers.ProvideMySQLConfig(config)
	mySQLConnection := providers.ProvideMySQLConnection(mySQLConfig)
	dbManager, err := providers.ProvideDBManager(mongoDBConnection, redisConnection, mySQLConnection)
	if err != nil {
		return nil, err
	}
	db := providers.ProvideMySQLDB(mySQLConnection)
	mySQLMigrator := providers.ProvideMySQLMigrator(db, mySQLConfig)
	migrationManager, err := providers.ProvideMigrationManager(config, mySQLMigrator)
	if err != nil {
		return nil, err
	}
	database := providers.ProvideMongoDB(mongoDBConnection)
	monAnMongoRepo := providers.ProvideMonAnMongoRepo(database)
	client := providers.ProvideRedisClient(redisConnection)
	redisCacheRepository := providers.ProvideRedisCacheRepository(client)
	cachedMonAnRepository := providers.ProvideCachedMonAnRepository(monAnMongoRepo, redisCacheRepository)
	iMonAnRepository := providers.ProvideMonAnRepository(cachedMonAnRepository)
	monAnUseCase := providers.ProvideMonAnUseCase(iMonAnRepository)
	monAnHandler := providers.ProvideMonAnHandler(monAnUseCase)
	healthHandler := providers.ProvideHealthHandler(dbManager)
	swaggerHandler := providers.ProvideSwaggerHandler()
	userMySQLRepo := providers.ProvideUserMySQLRepo(db)
	iUserRepository := providers.ProvideUserRepository(userMySQLRepo)
	tokenBlacklistService := providers.ProvideTokenBlacklistService(client, config)
	userUseCase := providers.ProvideUserUseCase(iUserRepository, tokenBlacklistService)
	jwtAuthMiddleware := providers.ProvideJWTAuth(config, tokenBlacklistService)
	userHandler := providers.ProvideUserHandler(userUseCase, jwtAuthMiddleware)
	loginAttemptService := providers.ProvideLoginAttemptService(client, config)
	emailVerificationService := providers.ProvideEmailVerificationService(client, config)
	emailService := providers.ProvideEmailService(config)
	authUseCase := providers.ProvideAuthUseCase(iUserRepository, jwtAuthMiddleware, loginAttemptService, emailVerificationService, emailService)
	authHandler := providers.ProvideAuthHandler(authUseCase)
	middlewareCollection := providers.ProvideMiddlewareCollection(config, jwtAuthMiddleware)
	app := &App{
		Config:           config,
		DBManager:        dbManager,
		MigrationManager: migrationManager,
		MonAnHandler:     monAnHandler,
		HealthHandler:    healthHandler,
		SwaggerHandler:   swaggerHandler,
		UserHandler:      userHandler,
		AuthHandler:      authHandler,
		Middlewares:      middlewareCollection,
		MongoConn:        mongoDBConnection,
		RedisConn:        redisConnection,
		MySQLConn:        mySQLConnection,
	}
	return app, nil
}

// wire.go:

// ServiceSet chứa các providers cho Domain Service layer
var ServiceSet = wire.NewSet(providers.ProvideLoginAttemptService, providers.ProvideTokenBlacklistService, providers.ProvideEmailVerificationService, providers.ProvideEmailService)

// MiddlewareSet chứa các providers cho Middleware layer
var MiddlewareSet = wire.NewSet(providers.ProvideJWTAuth, providers.ProvideMiddlewareCollection)

// MigrationSet chứa các providers cho Migration layer
var MigrationSet = wire.NewSet(providers.ProvideMySQLMigrator, providers.ProvideMigrationManager)

// ConfigSet chứa các providers cho Config layer
var ConfigSet = wire.NewSet(providers.ProvideConfig, providers.ProvideMongoDBConfig, providers.ProvideRedisConfig, providers.ProvideServerConfig, providers.ProvideMySQLConfig)

// DatabaseSet chứa các providers cho Database layer
var DatabaseSet = wire.NewSet(providers.ProvideMongoDBConnection, providers.ProvideRedisConnection, providers.ProvideMySQLConnection, providers.ProvideDBManager, providers.ProvideMongoDB, providers.ProvideRedisClient, providers.ProvideMySQLDB)

// RepositorySet chứa các providers cho Repository layer
var RepositorySet = wire.NewSet(providers.ProvideMonAnMongoRepo, providers.ProvideRedisCacheRepository, providers.ProvideCachedMonAnRepository, providers.ProvideMonAnRepository, providers.ProvideUserMySQLRepo, providers.ProvideUserRepository)

// UseCaseSet chứa các providers cho UseCase layer
var UseCaseSet = wire.NewSet(providers.ProvideMonAnUseCase, providers.ProvideUserUseCase, providers.ProvideAuthUseCase)

// HandlerSet chứa các providers cho Handler layer
var HandlerSet = wire.NewSet(providers.ProvideMonAnHandler, providers.ProvideHealthHandler, providers.ProvideSwaggerHandler, providers.ProvideUserHandler, providers.ProvideAuthHandler)

// App chứa tất cả dependencies đã được inject
type App struct {
	Config           *config.Config
	DBManager        *database.DBManager
	MigrationManager *migration.MigrationManager
	MonAnHandler     *handler.MonAnHandler
	HealthHandler    *handler.HealthHandler
	SwaggerHandler   *handler.SwaggerHandler
	UserHandler      *handler.UserHandler
	AuthHandler      *handler.AuthHandler
	Middlewares      *providers.MiddlewareCollection

	// Internal connections (để cleanup)
	MongoConn *database.MongoDBConnection
	RedisConn *database.RedisConnection
	MySQLConn *database.MySQLConnection
}
