// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"restaurant_project/internal/di/providers"
	"restaurant_project/internal/infrastructure/config"
	"restaurant_project/internal/infrastructure/database"
	"restaurant_project/internal/presentation/http/handler"
)

// Injectors from wire.go:

// InitializeApp là injector function - Wire sẽ tự động generate code
// để tạo App với tất cả dependencies
func InitializeApp() (*App, error) {
	config := providers.ProvideConfig()
	mongoDBConfig := providers.ProvideMongoDBConfig(config)
	mongoDBConnection := providers.ProvideMongoDBConnection(mongoDBConfig)
	redisConfig := providers.ProvideRedisConfig(config)
	redisConnection := providers.ProvideRedisConnection(redisConfig)
	dbManager, err := providers.ProvideDBManager(mongoDBConnection, redisConnection)
	if err != nil {
		return nil, err
	}
	database := providers.ProvideMongoDB(mongoDBConnection)
	monAnMongoRepo := providers.ProvideMonAnMongoRepo(database)
	client := providers.ProvideRedisClient(redisConnection)
	redisCacheRepository := providers.ProvideRedisCacheRepository(client)
	cachedMonAnRepository := providers.ProvideCachedMonAnRepository(monAnMongoRepo, redisCacheRepository)
	iMonAnRepository := providers.ProvideMonAnRepository(cachedMonAnRepository)
	monAnUseCase := providers.ProvideMonAnUseCase(iMonAnRepository)
	monAnHandler := providers.ProvideMonAnHandler(monAnUseCase)
	healthHandler := providers.ProvideHealthHandler(dbManager)
	swaggerHandler := providers.ProvideSwaggerHandler()
	middlewareCollection := providers.ProvideMiddlewareCollection(config)
	app := &App{
		Config:         config,
		DBManager:      dbManager,
		MonAnHandler:   monAnHandler,
		HealthHandler:  healthHandler,
		SwaggerHandler: swaggerHandler,
		Middlewares:    middlewareCollection,
		MongoConn:      mongoDBConnection,
		RedisConn:      redisConnection,
	}
	return app, nil
}

// wire.go:

// MiddlewareSet chứa các providers cho Middleware layer
var MiddlewareSet = wire.NewSet(providers.ProvideMiddlewareCollection)

// ConfigSet chứa các providers cho Config layer
var ConfigSet = wire.NewSet(providers.ProvideConfig, providers.ProvideMongoDBConfig, providers.ProvideRedisConfig, providers.ProvideServerConfig)

// DatabaseSet chứa các providers cho Database layer
var DatabaseSet = wire.NewSet(providers.ProvideMongoDBConnection, providers.ProvideRedisConnection, providers.ProvideDBManager, providers.ProvideMongoDB, providers.ProvideRedisClient)

// RepositorySet chứa các providers cho Repository layer
var RepositorySet = wire.NewSet(providers.ProvideMonAnMongoRepo, providers.ProvideRedisCacheRepository, providers.ProvideCachedMonAnRepository, providers.ProvideMonAnRepository)

// UseCaseSet chứa các providers cho UseCase layer
var UseCaseSet = wire.NewSet(providers.ProvideMonAnUseCase)

// HandlerSet chứa các providers cho Handler layer
var HandlerSet = wire.NewSet(providers.ProvideMonAnHandler, providers.ProvideHealthHandler, providers.ProvideSwaggerHandler)

// App chứa tất cả dependencies đã được inject
type App struct {
	Config         *config.Config
	DBManager      *database.DBManager
	MonAnHandler   *handler.MonAnHandler
	HealthHandler  *handler.HealthHandler
	SwaggerHandler *handler.SwaggerHandler
	Middlewares    *providers.MiddlewareCollection

	// Internal connections (để cleanup)
	MongoConn *database.MongoDBConnection
	RedisConn *database.RedisConnection
}
